use_frameworks!

platform :ios, '10.0'

# 忽略引入库的所有警告
inhibit_all_warnings!

target 'CCYunKit_Example' do
  pod 'CCYunKit', :path => '../'

  target 'CCYunKit_Tests' do
    inherit! :search_paths

    
  end
end
